USE ALFA;
GO

-- EJEMPLO 1

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CELULAR VARCHAR(20) NULL
);
GO


INSERT INTO CLIENTE(IDCLIENTE,NOMBRE) VALUES(5, 'GUSTAVO');
GO

SELECT * FROM CLIENTE;
GO

-- Esto da error

INSERT INTO CLIENTE(IDCLIENTE,CELULAR) VALUES(5, '994587127');
GO

INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CELULAR) VALUES(5, 'GUSTAVO', '982345768');
GO

SELECT * FROM CLIENTE;
GO

SELECT * FROM CLIENTE WHERE CELULAR IS NOT NULL;
GO

-- EJEMPLO 2

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL,
	NOMBRE VARCHAR(100) NOT NULL,
	CELULAR VARCHAR(20) NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(IDCLIENTE)
);
GO

INSERT INTO CLIENTE(IDCLIENTE,NOMBRE) VALUES(5, 'GUSTAVO');
INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CELULAR) VALUES(6, 'FERNANDO', '982345768');
INSERT INTO CLIENTE(IDCLIENTE,NOMBRE,CELULAR) VALUES(7, 'CESAR', NULL);
GO

SELECT * FROM CLIENTE;
GO

DROP TABLE VENTA;
GO

CREATE TABLE VENTA(
	IDVENTA INT NOT NULL,
	IDCLIENTE INT NOT NULL,
	IMPORTE DECIMAL(10,2) NOT NULL,
	CONSTRAINT PK_VENTA PRIMARY KEY (IDVENTA),
	CONSTRAINT FK_VENTA_CLIENTE FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
	ON DELETE CASCADE ON UPDATE CASCADE
);
GO

INSERT INTO VENTA VALUES(10,5,1000);
INSERT INTO VENTA VALUES(11,6,1500);
GO

SELECT * FROM VENTA;
GO

SELECT * FROM CLIENTE;
GO

DELETE FROM CLIENTE WHERE IDCLIENTE=7;
GO

DELETE FROM CLIENTE WHERE IDCLIENTE=5;
GO

UPDATE CLIENTE SET IDCLIENTE=11 WHERE IDCLIENTE=6;
GO








